### ISSUE TITLE
remove console... before release

### ISSUE THREAD

**Issue by nfalke** [coopjakob/cover#12]
https://github.com/coopjakob/cover/blob/378ab1aeb51c9b827e24d3d51842287c778e1fad/categoryicon/variant1.ts#L11

**Comment by coopjakob** [comment]
Debug messages are hidden in browser by default, and because the code is a bit quick and dirty and only live for 2 weeks, it feels nice to be able to debug instantly if someone experience a problem.

But I guess the whole mutation doesn't need to be included.

**Comment by coopjakob** [comment]
I'm automatically removing them from all .js files now ✌️

Using this Babel plugin.
https://babeljs.io/docs/en/babel-plugin-transform-remove-console
