### ISSUE TITLE
don't understand why this event is separated from the variation file. it can be added at at the same time as the variation

### ISSUE THREAD

**Issue by nfalke** [coopjakob/cover#14]
https://github.com/coopjakob/cover/blob/378ab1aeb51c9b827e24d3d51842287c778e1fad/categoryicon/event.ts#L35

**Comment by coopjakob** [comment]
The code in "events.ts" will be added to all variations. Both "variation 1" and original. This code will be added using Google Tag Manager.

The code in "variation1.ts" will be added only for 50% of the traffic, using Google Optimize.
