### ISSUE TITLE
getElementsByClassName is faster

### ISSUE THREAD

**Issue by nfalke** [coopjakob/cover#17]
https://github.com/coopjakob/cover/blob/d5a17d42e72fd4ba466adc8fe3a2a008bdf1c3ab/blackoutsearch/variant1.ts#L1

**Comment by coopjakob** [comment]
`getElementsByClassName` returns a `HTMLCollection` not a `Element`, I think that caused a problem last time I tried it.

It's also nice not to have different functions during develop. I often add and remove classes to find the right amount.

Maybe stuff like this can be automatically changed by Babel to improve performance?

**Comment by Pirulax** [comment]
You could index the first item in the selection, but I think youre better off with `querySelector`.

**Comment by coopjakob** [comment]
I'm using `querySelector` for everything now. Let me know if I shoudn't.
