### ISSUE TITLE
Is not one of the events enough? now the function will fire twice for the same change I think...

### ISSUE THREAD

**Issue by nfalke** [coopjakob/cover#19]
https://github.com/coopjakob/cover/blob/d5a17d42e72fd4ba466adc8fe3a2a008bdf1c3ab/blackoutsearch/variant1.ts#L5

**Comment by coopjakob** [comment]
👍

**Comment by coopjakob** [comment]
`change` is fired when you leave the field.
`input` is fired when you type something in the field.

`change` is needed if you paste something, instead of typing.
