### ISSUE TITLE
Doesn't disappear when you click on header

### ISSUE THREAD

**Issue by nfalke** [coopjakob/cover#20]
https://github.com/coopjakob/cover/blob/d5a17d42e72fd4ba466adc8fe3a2a008bdf1c3ab/blackoutsearch/variant1.ts#L71

when focusing the search field the modal shows even if I have not typed anything. then it does not dissapear when blurring the search field by a click on the header. that feels wierd.

**Comment by coopjakob** [comment]
I'll split this into two issues. Added #23

**Comment by coopjakob** [comment]
I'm adding this:
`searchInput.addEventListener('blur', experimentClose);`

But it will currently cause the black background to blink when you add something to the cart.

**Comment by coopjakob** [comment]
Outdated
