### ISSUE TITLE
Not sure if I understand why the run function is fired on page load. Seem to be enough to fire it in an event like input...

### ISSUE THREAD

**Issue by nfalke** [coopjakob/cover#22]
https://github.com/coopjakob/cover/blob/d5a17d42e72fd4ba466adc8fe3a2a008bdf1c3ab/blackoutsearch/variant1.ts#L71

**Comment by coopjakob** [comment]
The code is activated once you click on search bar, that's the reason why it need to fire instantly.

I've started to self invoke the function using the following code in later releases.

```
(function run() {
})();
```
