### ISSUE TITLE
Remove empty conditional block

### ISSUE THREAD

**Issue by laamzarescu** [coopjakob/cover#43]
[https://github.com/coopjakob/cover/blob/c49dbdef804d6f6f030f60780b37462441a4ed1c/events.ts#L78](https://github.com/coopjakob/cover/blob/c49dbdef804d6f6f030f60780b37462441a4ed1c/events.ts#L78)

Remove empty conditional block! It's useless. Try putting the negative case first.

```
if (!options.disconnect && isCallbackSent) {
  observer = new MutationObserver(mutations => {
    for (const { addedNodes } of mutations) {
    .......
```

**Comment by jensjakob** [comment]
`if (!options.disconnect && !isCallbackSent) {` will not trigger the code if `options.disconnect` is true and `isCallbackSent` is false.

**Comment by lamzarescu** [comment]
So do you want to add the observer even if the `isCallbackSent` is false? Because in your previous code, this case was ignored due to the fact that you checked only for `true` and `true`.

If this is what you want, than it's fine to use `if (!(options.disconnect && isCallbackSent)) {`

**Comment by lamzarescu** [comment]
Better stick with (!(options.disconnect && isCallbackSent)) {`
