### ISSUE TITLE
Consider using forEach in object loop.

### ISSUE THREAD

**Issue by lamzarescu** [coopjakob/cover#44]
[https://github.com/coopjakob/cover/blob/c49dbdef804d6f6f030f60780b37462441a4ed1c/events.ts#L82](https://github.com/coopjakob/cover/blob/c49dbdef804d6f6f030f60780b37462441a4ed1c/events.ts#L82)

https://alligator.io/js/foreach-vs-for-loops/

**Comment by coopjakob** [comment]
https://github.com/coopjakob/cover/blob/c49dbdef804d6f6f030f60780b37462441a4ed1c/events.ts#L82-L84

Maybe it can be changed to this:
```
mutations.forEach((mutation) => {
  mutation.addedNodes.forEach((node) => {
    if (node instanceof Element) {
      matchElementSelector(node);
    }
  });
});
```

But I guess it might be a way to flatten the nested forEach loops too!?

**Comment by lamzarescu** [comment]
I'm not aware with any way to flatten this particular case due to the fact that you need the explicit variables from the objects.
